# Generated by Django 3.2.8 on 2023-06-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='data_extraction.well'),
        ),
        migrations.AlterField(
            model_name='well',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='data_extraction.permit'),
        ),
    ]
