# Generated by Django 3.2.8 on 2023-06-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0002_auto_20230614_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='data_extraction.well'),
        ),
    ]
