# Generated by Django 3.2.8 on 2023-06-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0004_document_gov_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('well__id', 'document_name')},
        ),
        migrations.AddField(
            model_name='extractionaction',
            name='startLower',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='extractionaction',
            name='startUpper',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
