# Generated by Django 3.2.8 on 2023-06-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0005_auto_20230628_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionaction',
            name='offset_percent',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='extractionaction',
            name='offset_pixels',
            field=models.SmallIntegerField(null=True),
        ),
    ]
