# Generated by Django 3.2.8 on 2023-06-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0006_auto_20230629_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionactions',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='data_extraction.extractionaction'),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('page', 'extraction_method', 'value', 'text', 'unit', 'value2', 'text2', 'unit2', 'value3', 'text3', 'unit3', 'value4', 'text4', 'unit4')},
        ),
    ]
