# Generated by Django 3.2.8 on 2023-06-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0007_auto_20230629_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionactions',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='extractionactions',
            name='date_modified',
        ),
    ]
