# Generated by Django 3.2.8 on 2023-06-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0008_auto_20230629_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
