# Generated by Django 3.2.8 on 2023-07-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0009_alter_data_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionmethod',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='extractionaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initial Action'), (1, 'Immediately Next Text'), (2, 'Find Text'), (3, 'Get Value'), (4, 'Get Text Value'), (6, 'Next Data Row'), (5, 'Save Data'), (11, 'Table Header'), (12, 'Table Row'), (13, 'Table Cell')]),
        ),
    ]
