# Generated by Django 3.2.8 on 2023-07-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0011_auto_20230705_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('page', 'extraction_method', 'value', 'text', 'unit', 'value2', 'text2', 'unit2', 'value3', 'text3', 'unit3', 'value4', 'text4', 'unit4')},
        ),
    ]
