# Generated by Django 3.2.8 on 2023-07-06 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0012_alter_data_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='text11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text12',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text13',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text14',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text15',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text16',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text17',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text18',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text19',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='text20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='unit11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='eleventh_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='twelfth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit13',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='thirteenth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit14',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fourteenth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit15',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fifthteenth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit16',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sixteenth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit17',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='seventeenth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit18',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='eighteenth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit19',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='nineteenth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='unit20',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='twentieth_units', to='data_extraction.unit'),
        ),
        migrations.AddField(
            model_name='data',
            name='value11',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value12',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value13',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value14',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value15',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value16',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value17',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value18',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value19',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='value20',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
