# Generated by Django 3.2.8 on 2023-07-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0013_auto_20230706_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value12',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value13',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value14',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value15',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value16',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value17',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value18',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value19',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extracteddatatypes',
            name='value9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
